# Generated by Django 4.2.4 on 2023-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
    ]
