# Generated by Django 4.2.4 on 2023-08-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_nivel_posicion_usuario_nivel_usuario_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='posicion',
        ),
        migrations.AddField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
