# Generated by Django 4.2.4 on 2023-08-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_remove_nivel_nivel_remove_posicion_posicion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
