# Generated by Django 4.2.4 on 2023-08-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.nivel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.posicion'),
        ),
    ]
