# Generated by Django 4.2.4 on 2023-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_profile_nivel_profile_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
