# Generated by Django 4.2.4 on 2023-09-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0018_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
