# Generated by Django 4.2.4 on 2023-09-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0020_relationship'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_user', 'to_user'], name='sitio_relat_from_us_ad2270_idx'),
        ),
    ]
