# Generated by Django 4.2.4 on 2023-09-29 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0022_alter_relationship_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.AddField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
