# Generated by Django 4.2.4 on 2023-10-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0030_rename_user_dos_conversacion_destinatario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='verificado',
        ),
    ]
