# Generated by Django 4.2.4 on 2023-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0031_remove_post_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='estado',
            field=models.CharField(default='publicada', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(default='publicada', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
    ]
