# Generated by Django 4.2.4 on 2023-11-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0033_alter_profile_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permitir_mensajes_de_desconocidos',
            field=models.BooleanField(default=True),
        ),
    ]
